import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import SearchBar from "@/components/SearchBar";
import Link from "next/link";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body
                className={`${geistSans.variable} ${geistMono.variable} antialiased`}
            >
                <header className="py-3 px-2 mb-8 bg-slate-300">
                    <nav className="
                    flex items-center justify-between
                ">
                        <Link href="/" className="basis-1/3">Project GutenStobern</Link>

                        <SearchBar />

                        <div className="basis-1/3">
                            <p className="text-end">Navigation</p>
                        </div>
                    </nav>
                </header>

                {children}
            </body>
        </html>
    );
}
